trigger:
  batch: true
  branches:
    include:
    - master
schedules:
- cron: "0 0 * * *"
  branches:
    include:
    - master
  always: true
steps:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands
- checkout: self
  persistCredentials: true
  clean: true
- task: Npm@1
  inputs:
    command: install
- task: Npm@1
  inputs:
    command: custom
    customCommand: start
- powershell: |
   git config --global user.email "tomas@hubelbauer.net"
   git config --global user.name "Tomas Hubelbauer"
   git pull origin develop
   git add data.json
   git commit -m "Update data (Azure Pipelines)" -m "***NO_CI***"
   git push origin HEAD:master
