name: github-pages
on:
  push:
    branches:
    # Limit to the `master` branch
    - master
  schedule:
    # Run hourly
    - cron:  '0 * * * *'
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate GitHub Pages
      env:
        NO_CI: ${{ contains(github.event.head_commit.message, '***NO_CI***') }}
      run: |
        # Exit if ***NO_CI*** exists in the head commit message - GitHub Actions won't do this by themselves
        if $NO_CI; then
          exit
        fi
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "tomas@hubelbauer.net"
        git config --global user.name "Tomas Hubelbauer"
        # Check out the `master` branch because by default GitHub Actions checks out detached HEAD
        git checkout master
        # Run the script for refreshing the CSFD cinema data
        npm install
        npm start
        # Add generated GitHub Pages to Git stage
        git add data.json
        # Reset unstaged changes to prevent `git commit` from yelling if there's changes outside of `docs`
        git checkout -- .
        # Commit the changes to the Git repository to deploy GitHub Pages (if any)
        if git diff-index --quiet HEAD --; then
          exit
        fi
        git commit -m "Generate GitHub Pages (***NO_CI***)"
        # Use custom PAT because GitHub Pages won't deploy with the `GITHUB_TOKEN` PAT
        git remote set-url origin https://tomashubelbauer:${{ secrets.GITHUB_PAGES_PAT }}@github.com/TomasHubelbauer/puppeteer-csfd-scraper
        # Pull before pushing to integrate fast forward changes if any
        git pull
        # Push the changes to GitHub where it will cause another workflow which will kill itself immediately due to ***NO_CI***
        git push
        # Show GitHub Pages URL
        echo https://tomashubelbauer.github.io/puppeteer-csfd-scraper
