name: github-pages
on:
  push:
  schedule:
    # Run daily
    - cron:  '0 0 * * *'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate GitHub Pages
      run: |
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        # Check out the `master` branch because by default GitHub Actions checks out detached HEAD
        git checkout master
        # Run the script for refreshing the CSFD cinema data
        npm install
        npm start
        # Stage the generated data
        git add data
        git add study
        # Run the CRA version build
        rm -rf docs
        cd cra
        npm install
        npm run build
        cd ..
        mv cra/build docs
        # Stage the CRA build
        git add docs
        # Reset unstaged changes to prevent `git commit` from yelling if there's changes outside of `docs`
        git checkout -- .
        # Commit the changes to the Git repository to deploy GitHub Pages (if any)
        if git diff-index --quiet HEAD --; then
          exit
        fi
        git commit -m "Generate GitHub Pages"
        # Authenticate with GitHub using the out of the box workflow integration PAT (this one won't queue a GitHub Pages build though)
        git remote set-url origin https://:${{github.token}}@github.com/${{github.repository}}
        # Pull before pushing to integrate fast forward changes if any
        git pull --rebase
        # Push the changes to GitHub
        git push
